theme: "starter-hugo-academic"
# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Vegard Tørstad # Website name
baseurl: 'https://vegardtorstad.netlify.app/' # Website URL
copyright: © {year} Vegard Tørstad  # Footer text, e.g. '© {year} Me'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true




# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 1
  
[[menu.main]]
name = "Unpublished"
url = "/unpublished/"
weight = 2

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 3

[[menu.main]]
name = "Software"
url = "/software/"
weight = 4

[[menu.main]]
name = "Outreach"
url = "/outreach/" 
weight = 5

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 6

[[menu.main]]
name = "About"
url = "/about/"
weight = 7

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
