---
date: 2020-09-10
slug: xaringan-links
title: "Internal links in xaringan presentations"
output: html_document
categories:
        - xaringan
        - presentations
---

I am currently revising the <a href="https://resulumit.com/teaching/rmd_workshop.html" target="_blank"> slides</a> for the next iteration of my [workshop](ttps://resulumit.com/blog/rmd-workshop.html) on  writing reproducible research papers with R Markdown. It will take place at <a href="https://www.campus-luzern.ch/" target="_blank">Campus Luzern</a>, over two full days, in November 2020.

With over 200 slides in the presentation, I thought it is now time to introduce some internal links to facilitate the navigation across the different parts of the presentation, which is written with <a href="https://github.com/yihui/xaringan" target="_blank">`xaringan`</a>.

The linking syntax in R Markdown will not work here in `xaringan` presentations as we need to identify the target slides with the `name` argument. 

For example, assume that our presentation has a contents slide, to which we would like to link back from certain other slides, such as the final slides of each section.

We first name the contents slide. Note that multi-word names require hyphenation.

```md
---
name: contents-slide
## Contents
        
- Introduction
- Body
- Conclusion

---
```

We can than link back to the target slide as we would do in R Markdown documents.

```md
---
# Thank you!

- Go [back to Contents](#contents-slide)

---
```

This strategy can work in both directions---not only for linking backwards, but also forwards in a presentation.